[LINE]
apiURL = 'https://api.line.me/v2/bot/message/broadcast'
channel_access_token = ''

[Twitter]
CONSUMER_KEY = ''
CONSUMER_SECRET = ''

ACCESS_TOKEN = ''
ACCESS_SECRET = ''

UserID = ['abcid', 'defid', 'ghgid']
